id: d2b0bfa2ab2a4ec3bfbebf7fec4ecabb
initial_creation_type: ocr
source_metadata:
  volumes:
    7fa4f7d1a1b147e7ae981bd9b650eda5:
      base_file: v067.txt
      image_group_id: I1PD95912
      title: ''
      total_pages: 1529
      volume_number: 67
vol2fn:
  v067: v067.txt
